# Generated by Django 3.0.9 on 2020-08-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_mean', models.TextField(null=True)),
                ('valid', models.BooleanField()),
            ],
        ),
    ]
