# Generated by Django 3.0.9 on 2020-08-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='start_char',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
