# Generated by Django 3.0.9 on 2020-08-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200809_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='word_mean',
            field=models.TextField(null=True),
        ),
    ]
